### ISSUE TITLE
More command require

### ISSUE THREAD

**Issue by Pau1am** [BlossomMods/BlossomTpa#1]
Can you add the following command
- /tp (forced teleport to a player)
- /tphere (force a player to teleport to your side)
- /tpall (teleport all players to your side)

These commands can be provided to the server administrator for easier server management

**Comment by CodedSakura** [comment]
`/tp` is already a built-in command, but `/tphere` and `/tpall` sounds good!

**Comment by Pau1am** [comment]
Alternatively, you can add a command
- /tppos ~ ~ ~
To replace the /tp command in the vanilla version

**Comment by CodedSakura** [comment]
in my opinion changing vanilla behaviour is far from ideal, so i'll just implement `/tphere` and `/tpall` (both can also be done in vanilla, albeit not as easy as `/tp PlayerName` - `/tphere`: `/execute as PlayerName run tp @s`, `/tpall`: `/execute as @a run tp @s`)

**Comment by Pau1am** [comment]
You may have misunderstood my meaning. In fact, in the Vanilla version there are commands /tp ~ ~ ~ to teleport the player to a specific location. In Blossomtpa, commands/tp were instead forced to be teleported to a player. So I think it's possible to change /tp in the vanilla version to /tppos to distinguish between the two functions

**Comment by Pau1am** [comment]
Personally, I don't know much about programming. In my opinion, this is just a new command to achieve the function of the vanilla command. If this is too difficult, ignore the new advice

**Comment by CodedSakura** [comment]
it is of course possible to achieve the functionality of `/tp` but i have the opinion that the `/tp` command itself should remain unchanged (because if you're not expecting it to be changed, you'll be confused), thus a `/tppos` seems unnecessary

**Comment by Pau1am** [comment]
I understand. Then go ahead with your plan.😄

**Comment by CodedSakura** [comment]
i think i'll acutallly make `/tphere` accept multiple targets, so you could do `/tphere @a` for the same behaviour as your specified `/tpall`

**Comment by CodedSakura** [comment]
also i just realised that even the `/tphere` command is useless, as you can just do `/tp <Players> @s`...

so all 3 commands are not worth implementing as their behaviour is very simple to execute with the vanilla `/tp` command

**Comment by CodedSakura** [comment]
so to recap:
- instead of implemeting `/tp <player>`, you can use vanilla `/tp <player>`
- instead of implemeting `/tphere <player>`, you can use vanilla `/tp <player> @s`
- instead of implemeting `/tpall`, you can use vanilla `/tp @a @s`
