### ISSUE TITLE
[Question] Changing the color of the teleportation message

### ISSUE THREAD

**Issue by Riyuukii** [BlossomMods/BlossomTpa#10]
Is there a way to change the color the players received when sending/accepting tpa from purple to other colors? ty in advance!

**Comment by CodedSakura** [comment]
yes it is, done through BlossomLib, using the `colors` section of the [BlossomLib config](https://github.com/BlossomMods/BlossomLib/blob/main/README.md#config)
this will change all other message colors tho, so if you want to change the color of only those messages, i'm affraid that's currently not possible

**Comment by Riyuukii** [comment]
that should be fine for me, tysm!!
