### ISSUE TITLE
"Player can't receive tpas!"

### ISSUE THREAD

**Issue by UnusualHatter** [BlossomMods/BlossomTpa#13]
Hello Im having an issue with this mod running on my 1.21 modded server where any player who tries to use the tpa command receives this message. I never used a TPA mod, just the bukkit plugins so I don't know how to fix it.

![image](https://github.com/user-attachments/assets/cb011958-e929-48cf-8e79-dceb0ceeda08)

I have already configured the permissions instructed in the mod's wiki with luckperms, but the problem still persists. What am I doing wrong?

![image](https://github.com/user-attachments/assets/2fcc664b-0df0-448d-aa35-8c12fb1aaebe)

**Comment by CodedSakura** [comment]
the problem an oversight on my part, if you do `blossom.tpa`: `true`, it inadvertently sets `blossom.tpa.disallowed` to `true` aswell. i recommend explicitly adding a `blossom.tpa.disallowed`: `false`
