### ISSUE TITLE
tp command execution problem

### ISSUE THREAD

**Issue by Pau1am** [BlossomMods/BlossomTpa#2]
When I make a teleport request to another player using the /tp command, and the player accepts the request. I move in the middle and cannot cancel the teleport process, the teleport wait time is reset. I'm not sure if this is a bug, but I would expect the teleport to be interrupted when the player moves during the teleport. This problem also exists in BlossomHome mod and BlossomWarp mod.

**Comment by CodedSakura** [comment]
this is intended behaviour, to cancel a teleport you can use `/tpcancel`

**Comment by Pau1am** [comment]
However, sometimes, when I execute the teleport command, I may encounter monster attacks, or need to pause the teleport to perform an inadvertent operation before, and the teleport command cannot be canceled quickly, which will cause the teleporting command to keep showing on my screen, I think This is an area for improvement.

**Comment by CodedSakura** [comment]
alright, i'll add a config option in BlossomLib to toggle between it cancelling immediately when you move and the current behaviour

**Comment by CodedSakura** [comment]
added in BlossomLib 2.4.0
