### ISSUE TITLE
multi language support

### ISSUE THREAD

**Issue by Pau1am** [BlossomMods/BlossomTpa#3]
I would like the mod to provide separate language files for users to change the text information in the mod to other languages. I'd be happy to provide the mod with translations in Simplified Chinese and Traditional Chinese if this can be implemented. I would like this feature to be implemented in other BlossomMods at the same time.

**Comment by CodedSakura** [comment]
translations can be added via datapacks like so: https://github.com/NucleoidMC/Server-Translations/wiki/Add-translations-using-datapacks

the translation keys can be found here: https://github.com/BlossomMods/BlossomTpa/blob/main/src/main/resources/data/blossom/lang/en_us.json with detailed explanation at the bottom of the README

**Comment by CodedSakura** [comment]
If you wish, you could fork my mods, add the translation files in the /src/main/resources/data/blossom/lang folder, and create a pull request. that way the translations would be included into the mod & you wouldn't need to have a data pack for them

**Comment by CodedSakura** [comment]
closed by #4
