### ISSUE TITLE
Server crashes when using BlossomLib 2.5.1-fix and BlossomTPA

### ISSUE THREAD

**Issue by RealmKebab** [BlossomMods/BlossomTpa#8]
![image](https://github.com/BlossomMods/BlossomTpa/assets/73048123/29ce7148-526e-4f60-8691-0fc984bfd058)

**Comment by RealmKebab** [comment]
(here's crash report) https://mclo.gs/sB2geQ9

**Comment by CodedSakura** [comment]
fixed with BlossomLib 2.5.2
